# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 39fd4e916794d2831ff867c8fbb99a4dc057d2ecb691c9e3d2d7691f9783c36e9149694fd725cb47e6f72888e06cf9efa9ba38f5cdebf8eec00cb16b330adc74

test:
  secret_key_base: 984a94841b63e915af2158a43f66d93a3e43a24f44f1e5b2135150bdcc8b14850a6577e0866badf23397eca56287d860e72c5e6452ca6b154571feedeb9a0372

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
